[package]
name = "icn-governance"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
icn-common = { path = "../icn-common" }
icn-network = { path = "../icn-network" }
serde = { version = "1.0", features = ["derive"], optional = true }
sled = { version = "0.34", optional = true }
bincode = { version = "1.3", optional = true }

[features]
default = []
# The "serde" feature here enables serde for Proposal/Vote etc. if this crate is used directly.
# It's also a feature of icn-common, which these types use.
serde = ["dep:serde"]
persist-sled = ["dep:sled", "dep:bincode", "serde"] # persist-sled implies serde for the types
