[package]
name = "icn-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
icn-common = { path = "../icn-common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
bs58 = { version = "0.5.0", optional = true }
icn-mesh = { path = "../icn-mesh" }
icn-identity = { path = "../icn-identity" }
log = "0.4"
thiserror = "1.0"

libp2p = { version = "0.53", optional = true, features = [
    "tokio", 
    "gossipsub", 
    "kad", 
    "ping", 
    "noise", 
    "yamux", 
    "tcp",
    "dns",
    "macros"
]}

[dev-dependencies]
# No specific dev-dependencies here yet, but could add things like criterion for benchmarks
anyhow = "1.0"
libp2p = { version = "0.53", features = ["tokio", "tcp", "dns", "kad", "gossipsub", "noise", "yamux", "macros"] }

[features]
default = []
experimental-libp2p = [
    "dep:libp2p",
    "dep:bs58"
]
