repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D clippy::correctness -D clippy::suspicious -A dead_code -A unused_imports -A unused_variables
        language: system
        types: [rust]
        pass_filenames: false
