packages:
  # Frontend applications
  - 'apps/*'
  # Shared packages
  - 'packages/*'
  # Existing TypeScript SDK
  - 'crates/icn-api/client-sdk'

# Configuration
catalog:
  # Shared dependencies across all frontend packages
  react: "^18.2.0"
  react-dom: "^18.2.0"
  typescript: "^5.2.0"
  "@types/react": "^18.2.0"
  "@types/react-dom": "^18.2.0"
  vite: "^4.4.0"
  "@vitejs/plugin-react": "^4.0.0"
  tailwindcss: "^3.3.0"
  
  # React Native & Expo
  react-native: "0.72.6"
  expo: "~49.0.0"
  "@expo/webpack-config": "^19.0.0"
  
  # Tamagui
  "@tamagui/core": "^1.70.0"
  "@tamagui/config": "^1.70.0"
  "@tamagui/animations-react-native": "^1.70.0"
  
  # Tauri
  "@tauri-apps/api": "^1.5.0"
  "@tauri-apps/cli": "^1.5.0"
  
  # Testing & Linting
  eslint: "^8.50.0"
  prettier: "^3.0.0"
  "@typescript-eslint/eslint-plugin": "^6.0.0"
  "@typescript-eslint/parser": "^6.0.0"
  vitest: "^0.34.0"
  jest: "^29.0.0" 