[package]
name = "icn-proofstore"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
icn-common = { path = "../icn-common" }

[dev-dependencies]
tempfile = "3"

