name: Feature Request
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: dropdown
    id: crate-area
    attributes:
      label: Which crate or area does this feature relate to?
      description: Select the primary crate or area that this feature would affect
      options:
        - icn-common (Core data structures and errors)
        - icn-identity (DID management and cryptography)
        - icn-dag (Content-addressed storage)
        - icn-mesh (Distributed computing)
        - icn-runtime (Node runtime and Host ABI)
        - icn-governance (Proposals and voting)
        - icn-economics (Mana system and resource allocation)
        - icn-network (P2P networking and federation)
        - icn-reputation (Reputation scoring)
        - icn-node (Main node binary)
        - icn-cli (Command-line interface)
        - icn-ccl (Cooperative Contract Language)
        - icn-zk (Zero-knowledge proofs)
        - Documentation
        - CI/CD and tooling
        - Multi-crate/Cross-cutting
        - Other/Unsure
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](LINK_TO_CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 