[package]
name = "icn-ccl"
version = "0.1.0"
edition = "2021" # Assuming 2021 edition, adjust if needed
authors = ["InterCooperative Network <dev@intercooperative.network>"]
license = "Apache-2.0"
# description = "Compiler for the Cooperative Contract Language (CCL) to WASM"

[dependencies]
pest = "2.7" # Or the version you intend to use
pest_derive = "2.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
hex = "0.4" # Added for placeholder CID/hash generation in cli.rs
# Hashing
sha2 = "0.10"
# WASM generation
wasm-encoder = "0.233"
# wasm-tools = "1.208"  # Example, for WASM manipulation/validation

# Dependency for icn-common if metadata uses Did, Cid etc.
icn-common = { path = "../crates/icn-common" } # Adjust path as necessary

[dev-dependencies]
tempfile = "3.10"
# Needed to execute compiled WASM in tests
icn-runtime = { path = "../crates/icn-runtime" }
# Additional crates used in tests
icn-identity = { path = "../crates/icn-identity" }
icn-mesh = { path = "../crates/icn-mesh" }
tokio = { version = "1.0", features = ["full"] }
# For temporary DAG stores in integration tests
icn-dag = { path = "../crates/icn-dag" }
# Add test dependencies


