[package]
name = "icn-ccl"
version = "0.1.0"
edition = "2021" # Assuming 2021 edition, adjust if needed
authors.workspace = true
license.workspace = true
# description = "Compiler for the Cooperative Contract Language (CCL) to WASM"

[dependencies]
pest = "2.7" # Or the version you intend to use
pest_derive = "2.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
hex = "0.4" # Added for placeholder CID/hash generation in cli.rs
# wasm-encoder = "0.200" # Example, if generating WASM directly
# wasm-tools = "1.208"  # Example, for WASM manipulation/validation

# Dependency for icn-common if metadata uses Did, Cid etc.
icn-common = { path = "../icn-common" } # Adjust path as necessary

[dev-dependencies]
tempfile = "3.10"
# Add test dependencies 