[package]
name = "icn-ccl"
version.workspace = true
edition = "2021" # Assuming 2021 edition, adjust if needed
authors = ["InterCooperative Network <dev@intercooperative.network>"]
license = "Apache-2.0"
# description = "Compiler for the Cooperative Contract Language (CCL) to WASM"

[[bin]]
name = "demo_ccl"
path = "demo_ccl.rs"

[[bin]]
name = "demo_with_devnet"
path = "demo_with_devnet.rs"

[[bin]]
name = "test_parameter_fix"
path = "test_parameter_fix.rs"

[[bin]]
name = "test_working_features"
path = "test_working_features.rs"

[[bin]]
name = "test_governance_policy"
path = "test_governance_policy.rs"

[[bin]]
name = "test_ccl_devnet_integration" 
path = "test_ccl_devnet_integration.rs"

[[bin]]
name = "test_cooperative_contracts"
path = "test_cooperative_contracts.rs"

[[bin]]
name = "test_individual_contracts"
path = "test_individual_contracts.rs"

# [[bin]]
# name = "generate_ccl_job_spec"
# path = "src/bin/generate_ccl_job_spec.rs"


[dependencies]
pest = "2.7" # Or the version you intend to use
pest_derive = "2.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
hex = "0.4" # Added for placeholder CID/hash generation in cli.rs
# Logging
log = "0.4"
# Hashing
sha2 = "0.10"
# WASM generation
wasm-encoder = "0.233"
wasmparser = "0.121"
# HTTP client for job spec generator
reqwest = { workspace = true, features = ["blocking"] }
# wasm-tools = "1.208"  # Example, for WASM manipulation/validation

# Dependency for icn-common if metadata uses Did, Cid etc.
icn-common = { path = "../crates/icn-common" } # Adjust path as necessary

[dev-dependencies]
tempfile = "3.10"
# Needed to execute compiled WASM in tests
icn-runtime = { path = "../crates/icn-runtime", features = ["async"] }
# Additional crates used in tests
icn-identity = { path = "../crates/icn-identity" }
icn-mesh = { path = "../crates/icn-mesh" }
tokio = { version = "1.0", features = ["full"] }
# For temporary DAG stores in integration tests
icn-dag = { path = "../crates/icn-dag" }
# Add test dependencies
wasmtime = { version = "15", features = ["async"] }
# Templates for testing
icn-templates = { path = "../crates/icn-templates" }


