[package]
name = "icn-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
icn-common = { path = "../icn-common", version = "0.1.0" }
icn-api = { path = "../icn-api", version = "0.1.0" }
serde_json = "1.0"
