global:
  resolve_timeout: 5m

route:
  receiver: icn-alerts
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: icn-alerts
    email_configs:
      - to: alerts@intercooperative.network
