version: '3.8'

services:
  # Node A - Bootstrap node and primary HTTP gateway
  icn-node-a:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-a
    hostname: icn-node-a
    environment:
      - ICN_NODE_NAME=Federation-Node-A
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-a-key

      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5001:7845"  # HTTP API
      - "4001:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-a-data:/app/data
      - ./certs:/app/certs:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-a-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node B - Worker node
  icn-node-b:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-b
    hostname: icn-node-b
    environment:
      - ICN_NODE_NAME=Federation-Node-B
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-b-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5002:7845"  # HTTP API
      - "4002:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-b-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-b-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node C - Worker node
  icn-node-c:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-c
    hostname: icn-node-c
    environment:
      - ICN_NODE_NAME=Federation-Node-C
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-c-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5003:7845"  # HTTP API
      - "4003:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-c-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-c-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node D - Worker node
  icn-node-d:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-d
    hostname: icn-node-d
    environment:
      - ICN_NODE_NAME=Federation-Node-D
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-d-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5004:7845"  # HTTP API
      - "4004:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-d-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-d-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node E - Worker node
  icn-node-e:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-e
    hostname: icn-node-e
    environment:
      - ICN_NODE_NAME=Federation-Node-E
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-e-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5005:7845"  # HTTP API
      - "4005:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-e-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-e-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node F - Worker node
  icn-node-f:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-f
    hostname: icn-node-f
    environment:
      - ICN_NODE_NAME=Federation-Node-F
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-f-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5006:7845"  # HTTP API
      - "4006:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-f-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-f-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node G - Worker node
  icn-node-g:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-g
    hostname: icn-node-g
    environment:
      - ICN_NODE_NAME=Federation-Node-G
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-g-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5007:7845"  # HTTP API
      - "4007:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-g-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-g-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node H - Worker node
  icn-node-h:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-h
    hostname: icn-node-h
    environment:
      - ICN_NODE_NAME=Federation-Node-H
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-h-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5008:7845"  # HTTP API
      - "4008:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-h-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-h-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node I - Worker node
  icn-node-i:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-i
    hostname: icn-node-i
    environment:
      - ICN_NODE_NAME=Federation-Node-I
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-i-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5009:7845"  # HTTP API
      - "4009:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-i-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-i-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node J - Worker node
  icn-node-j:
    build:
      context: ..
      dockerfile: icn-devnet/Dockerfile
    container_name: icn-node-j
    hostname: icn-node-j
    environment:
      - ICN_NODE_NAME=Federation-Node-J
      - ICN_HTTP_LISTEN_ADDR=0.0.0.0:7845
      - ICN_P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/4001
      - ICN_ENABLE_P2P=true
      - ICN_ENABLE_MDNS=true
      - ICN_BOOTSTRAP_PEERS=/ip4/172.20.0.2/tcp/4001
      - ICN_STORAGE_BACKEND=memory
      - ICN_HTTP_API_KEY=devnet-j-key
      - RUST_LOG=info,icn_node=debug,icn_runtime=debug,icn_network=debug
    ports:
      - "5010:7845"  # HTTP API
      - "4010:4001"  # P2P networking
    networks:
      - icn-federation
    volumes:
      - node-j-data:/app/data
      - ./certs:/app/certs:ro
    depends_on:
      - icn-node-a
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-API-Key: devnet-j-key", "http://localhost:7845/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Prometheus for metrics monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: icn-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - icn-federation
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    profiles:
      - monitoring

  # Optional: Alertmanager for routing alerts
  alertmanager:
    image: prom/alertmanager:latest
    container_name: icn-alertmanager
    ports:
      - "9093:9093"
    networks:
      - icn-federation
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    profiles:
      - monitoring

  # Optional: Grafana for dashboard visualization
  grafana:
    image: grafana/grafana:latest
    container_name: icn-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=icnfederation
    ports:
      - "3000:3000"
    networks:
      - icn-federation
    volumes:
      - grafana-data:/var/lib/grafana
    profiles:
      - monitoring

  # Shared Postgres database for persistence testing
  postgres:
    image: postgres:15
    container_name: icn-postgres
    environment:
      - POSTGRES_USER=icn
      - POSTGRES_PASSWORD=icn_devnet
      - POSTGRES_DB=icn_devnet
    ports:
      - "5432:5432"
    networks:
      - icn-federation
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  icn-federation:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  node-a-data:
  node-b-data:
  node-c-data:
  node-d-data:
  node-e-data:
  node-f-data:
  node-g-data:
  node-h-data:
  node-i-data:
  node-j-data:
  postgres-data:
  grafana-data:
