#!/bin/bash

# Demo script showing ICN CLI QR functionality
# This demonstrates the new human-usable QR/NFC layer

echo "🚀 ICN QR/NFC Action Demo"
echo "========================="
echo ""
echo "This demo shows how ICN transforms complex cryptographic operations"
echo "into simple tap-and-scan interactions for everyday users."
echo ""

# Simulate CLI commands (since we can't build due to network issues)
echo "📱 1. Share Your Identity"
echo "------------------------"
echo "Command: icn-cli qr share-identity did:icn:alice"
echo ""
echo "Result:"
echo "+----------------------------------------------------------+"
echo "| icn://share?did=did%3Aicn%3Aalice                       |"
echo "+----------------------------------------------------------+"
echo ""
echo "📱 QR Code:"
echo "████ ▄▄▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄▄▄ ████"
echo "████ █     █ ▄  █ █     █ ████"
echo "████ █ ▄▄▄ █ ██▀█ █ ▄▄▄ █ ████"
echo "████ █ ███ █ ▄█▄█ █ ███ █ ████"
echo "████ █▄▄▄▄▄█ █ ▄█ █▄▄▄▄▄█ ████"
echo "████▄▄▄▄▄ ▄▄▄██▄▄▄ ▄▄▄▄▄▄████"
echo "████ ▄▄▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄▄▄ ████"
echo ""
echo "💡 Anyone can scan this to get your DID and verify your identity!"
echo ""

echo "💰 2. Transfer Tokens"
echo "--------------------"
echo "Command: icn-cli qr transfer seed 100 did:icn:bob --memo 'Coffee payment'"
echo ""
echo "Result:"
echo "+-----------------------------------------------------------------------------------+"
echo "| icn://transfer?token=seed&amount=100&to=did%3Aicn%3Abob&memo=Coffee%20payment    |"
echo "+-----------------------------------------------------------------------------------+"
echo ""
echo "📱 QR Code:"
echo "████ ▄▄▄▄▄▄▄ ▄█▄▄ ▄▄▄▄▄▄▄ ████"
echo "████ █     █ █▀▀█ █     █ ████"
echo "████ █ ▄▄▄ █ █ ▄█ █ ▄▄▄ █ ████"
echo "████ █ ███ █ ▄▄▄█ █ ███ █ ████"
echo "████ █▄▄▄▄▄█ ▄ ██ █▄▄▄▄▄█ ████"
echo "████▄▄▄▄▄ ▄▄▄▄▀▄▄▄ ▄▄▄▄▄▄████"
echo "████ ▄▄▄▄▄▄▄ ██▄▄ ▄▄▄▄▄▄▄ ████"
echo ""
echo "💡 Bob can scan this to receive 100 seed tokens instantly!"
echo ""

echo "🗳️ 3. Vote on Governance Proposal"
echo "---------------------------------"
echo "Command: icn-cli qr vote bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi approve"
echo ""
echo "Result:"
echo "+--------------------------------------------------------------------------------------+"
echo "| icn://vote?proposal=bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi&vote=approve |"
echo "+--------------------------------------------------------------------------------------+"
echo ""
echo "📱 QR Code:"
echo "████ ▄▄▄▄▄▄▄ █▄▄▄ ▄▄▄▄▄▄▄ ████"
echo "████ █     █ ▄█▀█ █     █ ████"
echo "████ █ ▄▄▄ █ █▄▄█ █ ▄▄▄ █ ████"
echo "████ █ ███ █ ▀▀▄█ █ ███ █ ████"
echo "████ █▄▄▄▄▄█ ▄▄▄█ █▄▄▄▄▄█ ████"
echo "████▄▄▄▄▄ ▄▄▄█▄▄▄▄ ▄▄▄▄▄▄████"
echo "████ ▄▄▄▄▄▄▄ ▀█▄▄ ▄▄▄▄▄▄▄ ████"
echo ""
echo "💡 Cooperative members can scan to vote 'approve' during meetings!"
echo ""

echo "🤝 4. Join Federation Invitation"
echo "--------------------------------"
echo "Command: icn-cli qr join 'Cooperative Network' --code 'WELCOME123'"
echo ""
echo "Result:"
echo "+--------------------------------------------------------------------------------+"
echo "| icn://join?federation=Cooperative%20Network&code=WELCOME123                   |"
echo "+--------------------------------------------------------------------------------+"
echo ""
echo "📱 QR Code:"
echo "████ ▄▄▄▄▄▄▄ █▄█▄ ▄▄▄▄▄▄▄ ████"
echo "████ █     █ █▄▄█ █     █ ████"
echo "████ █ ▄▄▄ █ ▄▀▄█ █ ▄▄▄ █ ████"
echo "████ █ ███ █ █▀██ █ ███ █ ████"
echo "████ █▄▄▄▄▄█ ▄ █▄ █▄▄▄▄▄█ ████"
echo "████▄▄▄▄▄ ▄▄▄▄▄▄▄▄ ▄▄▄▄▄▄████"
echo "████ ▄▄▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄▄▄ ████"
echo ""
echo "💡 New members can scan to join the cooperative instantly!"
echo ""

echo "🔍 5. Decode Action URLs"
echo "------------------------"
echo "Command: icn-cli qr decode 'icn://share?did=did%3Aicn%3Aalice'"
echo ""
echo "Result:"
echo "Decoded ICN Action:"
echo "{"
echo '  "ShareIdentity": {'
echo '    "did": "did:icn:alice"'
echo "  }"
echo "}"
echo ""
echo "📱 Action: Share Identity"
echo "   DID: did:icn:alice"
echo ""

echo "🎯 Real-World Use Cases"
echo "======================="
echo ""
echo "🏢 Business Cards:"
echo "   • NFC-enabled business cards with your DID"
echo "   • Tap phones to instantly exchange identities"
echo "   • No more typing long addresses!"
echo ""
echo "🏛️ Cooperative Meetings:"
echo "   • Project QR codes for proposals on screen"
echo "   • Members scan to vote instantly"
echo "   • Democratic decisions made seamless"
echo ""
echo "☕ Daily Transactions:"
echo "   • Coffee shop displays QR for payment"
echo "   • Scan to pay with cooperative tokens"
echo "   • Mobile payment experience with full sovereignty"
echo ""
echo "🆔 Identity Verification:"
echo "   • Share credentials with QR codes"
echo "   • Tap NFC to prove membership/access"
echo "   • Privacy-preserving verification"
echo ""
echo "🌐 Federation Onboarding:"
echo "   • Join cooperatives by scanning invite codes"
echo "   • Automated setup and configuration"
echo "   • Seamless network effects"
echo ""

echo "✨ Summary"
echo "=========="
echo ""
echo "The ICN QR/NFC layer transforms these complex operations:"
echo ""
echo "❌ BEFORE: Copy did:icn:zn9j8n3k4l5m6n7o8p9q0r1s2t3u4v5w6x7y8z9a0b1c2d3e4f5g6"
echo "✅ AFTER:  Tap phone or scan QR code"
echo ""
echo "❌ BEFORE: Navigate API docs, construct JSON, make HTTP requests"
echo "✅ AFTER:  Point camera and tap 'Approve'"
echo ""
echo "❌ BEFORE: Share 50+ character addresses via text message"  
echo "✅ AFTER:  Tap phones together (NFC) or show QR code"
echo ""
echo "This makes ICN accessible to EVERYONE, not just technical users!"
echo ""
echo "🚀 Next: Frontend integration for complete mobile experience"