[package]
name = "icn-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
icn-common = { path = "../icn-common" }
icn-mesh = { path = "../icn-mesh" }
icn-governance = { path = "../icn-governance" }
icn-identity = { path = "../icn-identity" }
icn-economics = { path = "../icn-economics" }
icn-network = { path = "../icn-network", features = ["experimental-libp2p"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full", "test-util"] }
async-trait = "0.1"
futures = "0.3"
downcast-rs = "1.2.0"
log = "0.4"
thiserror = "1.0"
libp2p = { version = "0.53", features = ["tokio", "gossipsub", "kad", "ping", "noise", "yamux", "tcp", "dns", "macros"] }

[dev-dependencies]
# No specific dev-dependencies here yet, but could add things like criterion for benchmarks
anyhow = "1.0"
libp2p = { version = "0.53", features = ["tokio", "tcp", "dns", "kad", "gossipsub", "noise", "yamux", "macros"] }

[features]
default = []
# TODO: Add features like "test-utils" if you export specific test helpers from this crate
