[package]
name = "icn-runtime"
version = "0.1.0"
edition = "2021"
authors = ["ICN Contributors"]
description = "Core runtime logic for ICN nodes, including Host ABI and job management."
license = "Apache-2.0"
readme = "README.md"

[dependencies]
icn-common = { path = "../icn-common" }
icn-identity = { path = "../icn-identity" }
icn-economics = { path = "../icn-economics" }
icn-mesh = { path = "../icn-mesh" }
icn-network = { path = "../icn-network", features = ["experimental-libp2p"] }
icn-dag = { path = "../icn-dag" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full", "test-util"] }
async-trait = "0.1.77"
log = "0.4"
thiserror = "1.0"
libp2p = { version = "0.53.2", optional = true }
downcast-rs = "2.0.1"
futures = "0.3"

[dev-dependencies]
anyhow = "1.0.75"
# temp-dir = "0.1"

[features]
default = []
# TODO: Define features if needed, e.g., for different execution environments or optional components.
enable-libp2p = ["dep:libp2p"]

# Integration tests for cross-node functionality
[[test]]
name = "cross_node_job_execution"
path = "tests/cross_node_job_execution.rs"
required-features = ["enable-libp2p"]
