# Clippy settings for icn-runtime

disallowed-methods = [
    { path = "std::time::SystemTime::now", reason = "use deterministic time provider" },
    { path = "fastrand::f64", reason = "use deterministic RNG" },
    { path = "fastrand::u64", reason = "use deterministic RNG" },
    { path = "fastrand::u32", reason = "use deterministic RNG" },
    { path = "fastrand::usize", reason = "use deterministic RNG" },
    { path = "fastrand::fill", reason = "use deterministic RNG" }
]
