name: ICN CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Install clippy component
        run: rustup component add clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features --workspace --exclude icn-integration-tests

      - name: Run icn-cli integration tests
        run: cargo test --all-features -p icn-cli

      - name: Run CLI-node integration tests
        run: cargo test --all-features -p icn-integration-tests --test cli_node

      - name: Run benchmarks
        run: cargo bench --workspace --all-features

      - name: Start devnet (nightly only)
        if: matrix.rust == 'nightly'
        run: |
          ./icn-devnet/launch_federation.sh --start-only
      - name: Run integration tests (nightly only)
        if: matrix.rust == 'nightly'
        env:
          ICN_DEVNET_RUNNING: "true"
        run: cargo test --all-features -p icn-integration-tests -- --nocapture
      - name: Stop devnet (nightly only)
        if: matrix.rust == 'nightly'
        run: docker-compose -f icn-devnet/docker-compose.yml down --volumes --remove-orphans

      - name: Build release (nightly only, for early detection of issues)
        if: matrix.rust == 'nightly'
        run: cargo build --release --all-features --workspace

  libp2p_tests:
    name: Libp2p Feature Tests
    needs: test_and_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
      - name: Run libp2p tests
        run: cargo test -p icn-network --features libp2p
