name: "Copilot Setup Steps"

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake pkg-config libssl-dev lldb librocksdb-dev

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.0.0

      - name: Verify pnpm is installed
        run: pnpm --version

      - name: Install dependencies using pnpm
        run: |
          if [ -f pnpm-workspace.yaml ]; then
            echo "Found pnpm-workspace.yaml"
          fi
          pnpm install --frozen-lockfile || pnpm install

      - name: Fetch Rust dependencies
        run: cargo fetch

      - name: Show versions for debugging
        run: |
          echo "Rust:"
          rustc --version
          cargo --version

          echo "Node:"
          node --version
          npm --version || true

          echo "pnpm:"
          pnpm --version
