name: "Copilot Setup Steps"

on:
  workflow_call:  # This is triggered by GitHub Copilot agent

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake pkg-config libssl-dev lldb librocksdb-dev

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable and prepare Corepack (for pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@8.0.0 --activate

      - name: Install TypeScript/JavaScript dependencies with pnpm
        run: pnpm install

      - name: Fetch Rust dependencies
        run: cargo fetch

      - name: Show tool versions for debugging
        run: |
          echo "✅ Rust:"
          rustc --version
          cargo --version

          echo "✅ Node:"
          node --version
          npm --version || true

          echo "✅ pnpm:"
          pnpm --version

          echo "✅ clang:"
          clang --version || true
