name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - scripts/**
  pull_request:
    branches: [develop]
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - scripts/**

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 🚀 Run ICN environment setup
        run: ./scripts/copilot-env-setup.sh
        working-directory: ${{ github.workspace }}

      - name: 📤 Upload setup log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: icn-setup-log
          path: /tmp/icn-setup.log
